
require:
  - rubocop-rails
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
Style/RedundantFetchBlock:
  Exclude:
    - config/puma.rb

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
